export const eventDetails = [
  {
    eventID: 431,
    eventTitle: "Coldplay Concert — Music of the Spheres",
    image: "/assets/images/music.png",
    eventCategory: "Music",
    address: "DY Patil Stadium, Mumbai-400614",
    city: "Mumbai",
    totalSpots: 50000,
    spotsLeft: 12400,
    price: 2999,
    date: "Mar 22",
    time: "7:00 PM",
    roomsLeft: 248,
    compatibilityScore: 96,
    isNewcomerFriendly: false,
    isTrending: true,
    isFeatured: true,
    isVerified: true,
    tags: ["music", "concert", "celebrity", "live"],
    coverGradient: "linear-gradient(135deg,#0A1628,#1E3A8A)",
    organizerName: "Wizcraft International",
  },
  {
    eventID: 432,
    eventTitle: "New in Bangalore? Weekend Brunch Meetup",
    image: "/assets/images/food.png",
    eventCategory: "Social",
    address: "The Hole in the Wall Café, Koramangala, Bangalore-560034",
    city: "Bangalore",
    totalSpots: 30,
    spotsLeft: 18,
    price: 199,
    date: "Mar 8",
    time: "11:00 AM",
    roomsLeft: 3,
    compatibilityScore: 91,
    isNewcomerFriendly: true,
    isTrending: false,
    isFeatured: false,
    isVerified: true,
    tags: ["social", "brunch", "newcomer"],
    coverGradient: "linear-gradient(135deg,#2D0A5E,#1A0635)",
    organizerName: "BLR Social Club",
  },
  {
    eventID: 433,
    eventTitle: "City Explorer Walk — Heritage Trail",
    image: "/assets/images/art.png",
    eventCategory: "Outdoors",
    address: "MG Road Metro Station, Bangalore-560001",
    city: "Bangalore",
    totalSpots: 20,
    spotsLeft: 12,
    price: 0,
    date: "Mar 9",
    time: "7:00 AM",
    roomsLeft: 2,
    compatibilityScore: 85,
    isNewcomerFriendly: true,
    isTrending: false,
    isFeatured: false,
    isVerified: true,
    tags: ["outdoors", "walking", "newcomer", "heritage"],
    coverGradient: "linear-gradient(135deg,#064E3B,#065F46)",
    organizerName: "Explore BLR",
  },
  {
    eventID: 434,
    eventTitle: "Board Game Night — Make New Friends!",
    image: "/assets/images/nightlife.png",
    eventCategory: "Social",
    address: "Dice & Decks Café, Indiranagar, Bangalore-560038",
    city: "Bangalore",
    totalSpots: 40,
    spotsLeft: 22,
    price: 149,
    date: "Mar 10",
    time: "6:00 PM",
    roomsLeft: 4,
    compatibilityScore: 88,
    isNewcomerFriendly: true,
    isTrending: false,
    isFeatured: false,
    isVerified: true,
    tags: ["games", "social", "newcomer", "indoor"],
    coverGradient: "linear-gradient(135deg,#1E1A06,#3D3510)",
    organizerName: "Playful Bangalore",
  },
  {
    eventID: 435,
    eventTitle: "Indie Night — Live Bands at Humming Tree",
    image: "/assets/images/music.png",
    eventCategory: "Music",
    address: "Humming Tree, Indiranagar, Bangalore-560038",
    city: "Bangalore",
    totalSpots: 200,
    spotsLeft: 8,
    price: 499,
    date: "Mar 11",
    time: "8:00 PM",
    roomsLeft: 6,
    compatibilityScore: 94,
    isNewcomerFriendly: false,
    isTrending: true,
    isFeatured: false,
    isVerified: true,
    tags: ["music", "nightlife", "live", "indie"],
    coverGradient: "linear-gradient(135deg,#1E1040,#2D1060)",
    organizerName: "BLR Gigs",
  },
  {
    eventID: 436,
    eventTitle: "AI & ML Builders Hackathon 2025",
    image: "/assets/images/tech.png",
    eventCategory: "Tech",
    address: "91Springboard, HSR Layout, Bangalore-560102",
    city: "Bangalore",
    totalSpots: 150,
    spotsLeft: 42,
    price: 0,
    date: "Mar 15",
    time: "9:00 AM",
    roomsLeft: 12,
    compatibilityScore: 89,
    isNewcomerFriendly: false,
    isTrending: true,
    isFeatured: true,
    isVerified: true,
    tags: ["tech", "hackathon", "ai", "ml"],
    coverGradient: "linear-gradient(135deg,#172554,#1E3A8A)",
    organizerName: "DevCircle India",
  },
  {
    eventID: 437,
    eventTitle: "Speed Friending — Meet 20 New People",
    image: "/assets/images/social.png",
    eventCategory: "Social",
    address: "Arbor Brewing Company, Koramangala, Bangalore-560034",
    city: "Bangalore",
    totalSpots: 40,
    spotsLeft: 8,
    price: 299,
    date: "Mar 12",
    time: "5:00 PM",
    roomsLeft: 4,
    compatibilityScore: 82,
    isNewcomerFriendly: true,
    isTrending: true,
    isFeatured: false,
    isVerified: true,
    tags: ["social", "newcomer", "networking", "friends"],
    coverGradient: "linear-gradient(135deg,#3D0A0A,#7F1D1D)",
    organizerName: "Friend Finder BLR",
  },
  {
    eventID: 438,
    eventTitle: "Photography Walk — Cubbon Park",
    image: "/assets/images/art.png",
    eventCategory: "Arts",
    address: "Cubbon Park Main Gate, Bangalore-560001",
    city: "Bangalore",
    totalSpots: 15,
    spotsLeft: 9,
    price: 99,
    date: "Mar 14",
    time: "6:30 AM",
    roomsLeft: 2,
    compatibilityScore: 96,
    isNewcomerFriendly: true,
    isTrending: false,
    isFeatured: false,
    isVerified: true,
    tags: ["photography", "outdoors", "arts", "morning"],
    coverGradient: "linear-gradient(135deg,#0A2E1A,#064E3B)",
    organizerName: "Lens & Light BLR",
  },
  {
    eventID: 439,
    eventTitle: "React & Next.js Workshop for Builders",
    image: "/assets/images/tech.png",
    eventCategory: "Tech",
    address: "WeWork Galaxy, Whitefield, Bangalore-560066",
    city: "Bangalore",
    totalSpots: 50,
    spotsLeft: 21,
    price: 399,
    date: "Mar 16",
    time: "10:00 AM",
    roomsLeft: 5,
    compatibilityScore: 93,
    isNewcomerFriendly: false,
    isTrending: false,
    isFeatured: false,
    isVerified: true,
    tags: ["tech", "workshop", "coding", "react"],
    coverGradient: "linear-gradient(135deg,#172554,#1E40AF)",
    organizerName: "CodeCraft India",
  },
  {
    eventID: 440,
    eventTitle: "Open Mic Night — Poetry & Music",
    image: "/assets/images/music.png",
    eventCategory: "Arts",
    address: "Atta Galatta, Jayanagar, Bangalore-560041",
    city: "Bangalore",
    totalSpots: 60,
    spotsLeft: 34,
    price: 149,
    date: "Mar 17",
    time: "7:00 PM",
    roomsLeft: 3,
    compatibilityScore: 90,
    isNewcomerFriendly: true,
    isTrending: false,
    isFeatured: false,
    isVerified: true,
    tags: ["arts", "music", "poetry", "openmic"],
    coverGradient: "linear-gradient(135deg,#1A0A2E,#4C1D95)",
    organizerName: "Stage & Soul BLR",
  },
  {
    eventID: 441,
    eventTitle: "Sunrise Trek — Skandagiri Hills",
    image: "/assets/images/adventure.png",
    eventCategory: "Outdoors",
    address: "Skandagiri Base Camp, Chikkaballapur-562101",
    city: "Bangalore",
    totalSpots: 25,
    spotsLeft: 11,
    price: 599,
    date: "Mar 22",
    time: "12:00 AM",
    roomsLeft: 3,
    compatibilityScore: 95,
    isNewcomerFriendly: false,
    isTrending: true,
    isFeatured: false,
    isVerified: true,
    tags: ["trekking", "outdoors", "adventure", "morning"],
    coverGradient: "linear-gradient(135deg,#0A2E1A,#065F46)",
    organizerName: "Trek India BLR",
  },
  {
    eventID: 442,
    eventTitle: "Startup Founders Networking Night",
    image: "/assets/images/tech.png",
    eventCategory: "Professional",
    address: "BHIVE Workspace, HSR Layout, Bangalore-560102",
    city: "Bangalore",
    totalSpots: 80,
    spotsLeft: 35,
    price: 499,
    date: "Mar 18",
    time: "6:30 PM",
    roomsLeft: 7,
    compatibilityScore: 87,
    isNewcomerFriendly: false,
    isTrending: true,
    isFeatured: false,
    isVerified: true,
    tags: ["startup", "networking", "professional", "tech"],
    coverGradient: "linear-gradient(135deg,#0C1A3D,#1E3A8A)",
    organizerName: "Founders Circle India",
  },
  {
    eventID: 443,
    eventTitle: "Koramangala Café Hopping Tour",
    image: "/assets/images/food.png",
    eventCategory: "Food",
    address: "Meeting Point: Starbucks, Koramangala, Bangalore",
    city: "Bangalore",
    totalSpots: 20,
    spotsLeft: 14,
    price: 249,
    date: "Mar 19",
    time: "3:00 PM",
    roomsLeft: 2,
    compatibilityScore: 88,
    isNewcomerFriendly: true,
    isTrending: false,
    isFeatured: false,
    isVerified: true,
    tags: ["food", "cafe", "social", "newcomer"],
    coverGradient: "linear-gradient(135deg,#3D1A06,#7C3503)",
    organizerName: "Foodie BLR",
  },
  {
    eventID: 444,
    eventTitle: "Morning Yoga & Meditation — Cubbon Park",
    image: "/assets/images/health.png",
    eventCategory: "Wellness",
    address: "Cubbon Park Lawn Area, Bangalore-560001",
    city: "Bangalore",
    totalSpots: 30,
    spotsLeft: 17,
    price: 99,
    date: "Mar 20",
    time: "6:00 AM",
    roomsLeft: 2,
    compatibilityScore: 84,
    isNewcomerFriendly: true,
    isTrending: false,
    isFeatured: false,
    isVerified: true,
    tags: ["wellness", "yoga", "meditation", "morning", "outdoor"],
    coverGradient: "linear-gradient(135deg,#064E3B,#0F766E)",
    organizerName: "Zen BLR",
  },
  {
    eventID: 445,
    eventTitle: "Street Photography Masterclass",
    image: "/assets/images/art.png",
    eventCategory: "Arts",
    address: "Commercial Street, Bangalore-560001",
    city: "Bangalore",
    totalSpots: 12,
    spotsLeft: 5,
    price: 299,
    date: "Mar 20",
    time: "8:00 AM",
    roomsLeft: 1,
    compatibilityScore: 91,
    isNewcomerFriendly: false,
    isTrending: false,
    isFeatured: false,
    isVerified: true,
    tags: ["photography", "arts", "workshop", "street"],
    coverGradient: "linear-gradient(135deg,#1A0A2E,#3B0764)",
    organizerName: "Lens & Light BLR",
  },
  {
    eventID: 446,
    eventTitle: "Diljit Dosanjh — Dil-Luminati Tour",
    image: "/assets/images/music.png",
    eventCategory: "Music",
    address: "Jawaharlal Nehru Stadium, Delhi-110003",
    city: "Delhi",
    totalSpots: 40000,
    spotsLeft: 8200,
    price: 1999,
    date: "Apr 5",
    time: "7:30 PM",
    roomsLeft: 312,
    compatibilityScore: 93,
    isNewcomerFriendly: false,
    isTrending: true,
    isFeatured: true,
    isVerified: true,
    tags: ["music", "concert", "celebrity", "punjabi"],
    coverGradient: "linear-gradient(135deg,#1A0535,#4C0F8F)",
    organizerName: "Live Nation India",
  },
  {
    eventID: 447,
    eventTitle: "Delhi Food Festival 2025",
    image: "/assets/images/food.png",
    eventCategory: "Food",
    address: "Jawaharlal Nehru University Campus, Delhi-110067",
    city: "Delhi",
    totalSpots: 500,
    spotsLeft: 213,
    price: 199,
    date: "Mar 28",
    time: "12:00 PM",
    roomsLeft: 18,
    compatibilityScore: 86,
    isNewcomerFriendly: true,
    isTrending: true,
    isFeatured: false,
    isVerified: true,
    tags: ["food", "festival", "social", "newcomer"],
    coverGradient: "linear-gradient(135deg,#3D1A06,#92400E)",
    organizerName: "Delhi Events Co.",
  },
  {
    eventID: 448,
    eventTitle: "Mumbai Pub Crawl — Bandra Edition",
    image: "/assets/images/nightlife.png",
    eventCategory: "Nightlife",
    address: "Meeting Point: Carter Road, Bandra, Mumbai-400050",
    city: "Mumbai",
    totalSpots: 60,
    spotsLeft: 22,
    price: 799,
    date: "Mar 21",
    time: "8:00 PM",
    roomsLeft: 5,
    compatibilityScore: 79,
    isNewcomerFriendly: false,
    isTrending: true,
    isFeatured: false,
    isVerified: true,
    tags: ["nightlife", "social", "drinks", "bandra"],
    coverGradient: "linear-gradient(135deg,#1A0535,#6B21A8)",
    organizerName: "Mumbai Nights",
  },
  {
    eventID: 449,
    eventTitle: "Pune Startup Weekend 2025",
    image: "/assets/images/education.png",
    eventCategory: "Professional",
    address: "CoWork Café, Baner, Pune-411045",
    city: "Pune",
    totalSpots: 100,
    spotsLeft: 44,
    price: 999,
    date: "Mar 29",
    time: "9:00 AM",
    roomsLeft: 8,
    compatibilityScore: 88,
    isNewcomerFriendly: false,
    isTrending: false,
    isFeatured: false,
    isVerified: true,
    tags: ["startup", "professional", "tech", "weekend"],
    coverGradient: "linear-gradient(135deg,#0C1A3D,#1D4ED8)",
    organizerName: "Startup Pune",
  },
  {
    eventID: 450,
    eventTitle: "Karaoke Night — Sing Your Heart Out",
    image: "/assets/images/social.png",
    eventCategory: "Social",
    address: "The Humming Bird, Indiranagar, Bangalore-560038",
    city: "Bangalore",
    totalSpots: 50,
    spotsLeft: 28,
    price: 349,
    date: "Mar 23",
    time: "7:30 PM",
    roomsLeft: 4,
    compatibilityScore: 83,
    isNewcomerFriendly: true,
    isTrending: false,
    isFeatured: false,
    isVerified: true,
    tags: ["karaoke", "music", "social", "fun", "newcomer"],
    coverGradient: "linear-gradient(135deg,#4A044E,#86198F)",
    organizerName: "Fun Nights BLR",
  },
  {
    eventID: 451,
    eventTitle: "Cycling Tour — Nandi Hills at Dawn",
    image: "/assets/images/adventure.png",
    eventCategory: "Outdoors",
    address: "Nandi Hills Base, Chikkaballapur-562103",
    city: "Bangalore",
    totalSpots: 20,
    spotsLeft: 7,
    price: 799,
    date: "Mar 24",
    time: "4:00 AM",
    roomsLeft: 2,
    compatibilityScore: 92,
    isNewcomerFriendly: false,
    isTrending: false,
    isFeatured: false,
    isVerified: true,
    tags: ["cycling", "outdoors", "adventure", "morning"],
    coverGradient: "linear-gradient(135deg,#0A2E1A,#14532D)",
    organizerName: "Pedal BLR",
  },
  {
    eventID: 452,
    eventTitle: "Pottery Workshop for Beginners",
    image: "/assets/images/art.png",
    eventCategory: "Arts",
    address: "Claymade Studio, JP Nagar, Bangalore-560078",
    city: "Bangalore",
    totalSpots: 12,
    spotsLeft: 6,
    price: 599,
    date: "Mar 25",
    time: "11:00 AM",
    roomsLeft: 1,
    compatibilityScore: 86,
    isNewcomerFriendly: true,
    isTrending: false,
    isFeatured: false,
    isVerified: true,
    tags: ["arts", "pottery", "workshop", "creative", "newcomer"],
    coverGradient: "linear-gradient(135deg,#3D1A06,#92400E)",
    organizerName: "Claymade Studio",
  },
  {
    eventID: 453,
    eventTitle: "Hyderabad Biryani Food Walk",
    image: "/assets/images/food.png",
    eventCategory: "Food",
    address: "Charminar, Old City, Hyderabad-500002",
    city: "Hyderabad",
    totalSpots: 25,
    spotsLeft: 13,
    price: 299,
    date: "Mar 26",
    time: "12:30 PM",
    roomsLeft: 2,
    compatibilityScore: 89,
    isNewcomerFriendly: true,
    isTrending: true,
    isFeatured: false,
    isVerified: true,
    tags: ["food", "biryani", "walk", "hyderabad", "newcomer"],
    coverGradient: "linear-gradient(135deg,#3D1206,#7C1F0A)",
    organizerName: "HYD Food Tours",
  },
  {
    eventID: 454,
    eventTitle: "Stand-Up Comedy Night — Biswa Kalyan Rath",
    image: "/assets/images/social.png",
    eventCategory: "Entertainment",
    address: "Chowdiah Memorial Hall, Bangalore-560003",
    city: "Bangalore",
    totalSpots: 800,
    spotsLeft: 145,
    price: 699,
    date: "Apr 2",
    time: "7:00 PM",
    roomsLeft: 22,
    compatibilityScore: 91,
    isNewcomerFriendly: false,
    isTrending: true,
    isFeatured: true,
    isVerified: true,
    tags: ["comedy", "entertainment", "standup", "live"],
    coverGradient: "linear-gradient(135deg,#1C1917,#44403C)",
    organizerName: "OML Entertainment",
  },
  {
    eventID: 455,
    eventTitle: "Salsa & Bachata Dance Workshop",
    image: "/assets/images/art.png",
    eventCategory: "Dance",
    address: "Rythem Dance Studio, Koramangala, Bangalore-560034",
    city: "Bangalore",
    totalSpots: 30,
    spotsLeft: 16,
    price: 349,
    date: "Mar 27",
    time: "6:00 PM",
    roomsLeft: 3,
    compatibilityScore: 84,
    isNewcomerFriendly: true,
    isTrending: false,
    isFeatured: false,
    isVerified: true,
    tags: ["dance", "salsa", "workshop", "social", "newcomer"],
    coverGradient: "linear-gradient(135deg,#4A0520,#9D174D)",
    organizerName: "Dance BLR",
  },
  {
    eventID: 456,
    eventTitle: "Book Club Meetup — Monthly Edition",
    image: "/assets/images/social.png",
    eventCategory: "Social",
    address: "Blossom Book House, Church Street, Bangalore-560001",
    city: "Bangalore",
    totalSpots: 20,
    spotsLeft: 11,
    price: 0,
    date: "Mar 30",
    time: "4:00 PM",
    roomsLeft: 1,
    compatibilityScore: 81,
    isNewcomerFriendly: true,
    isTrending: false,
    isFeatured: false,
    isVerified: true,
    tags: ["books", "reading", "social", "newcomer"],
    coverGradient: "linear-gradient(135deg,#1C1917,#292524)",
    organizerName: "BLR Book Club",
  },
  {
    eventID: 457,
    eventTitle: "Chennai Classical Music Evening",
    image: "/assets/images/music.png",
    eventCategory: "Music",
    address: "Music Academy, T. Nagar, Chennai-600017",
    city: "Chennai",
    totalSpots: 300,
    spotsLeft: 120,
    price: 249,
    date: "Apr 1",
    time: "6:30 PM",
    roomsLeft: 9,
    compatibilityScore: 78,
    isNewcomerFriendly: true,
    isTrending: false,
    isFeatured: false,
    isVerified: true,
    tags: ["music", "classical", "cultural", "newcomer"],
    coverGradient: "linear-gradient(135deg,#1A0A2E,#3B1275)",
    organizerName: "Chennai Arts Foundation",
  },
  {
    eventID: 458,
    eventTitle: "Badminton Tournament — Open Category",
    image: "/assets/images/sports.png",
    eventCategory: "Sports",
    address: "Kanteerava Indoor Stadium, Bangalore-560001",
    city: "Bangalore",
    totalSpots: 64,
    spotsLeft: 28,
    price: 199,
    date: "Apr 6",
    time: "8:00 AM",
    roomsLeft: 6,
    compatibilityScore: 87,
    isNewcomerFriendly: false,
    isTrending: false,
    isFeatured: false,
    isVerified: true,
    tags: ["sports", "badminton", "tournament", "fitness"],
    coverGradient: "linear-gradient(135deg,#0C2A3D,#164E63)",
    organizerName: "BLR Sports Club",
  },
  {
    eventID: 459,
    eventTitle: "Mindfulness & Journaling Retreat",
    image: "/assets/images/health.png",
    eventCategory: "Wellness",
    address: "Svaastha Wellness, Whitefield, Bangalore-560066",
    city: "Bangalore",
    totalSpots: 15,
    spotsLeft: 8,
    price: 899,
    date: "Apr 7",
    time: "9:00 AM",
    roomsLeft: 1,
    compatibilityScore: 83,
    isNewcomerFriendly: true,
    isTrending: false,
    isFeatured: false,
    isVerified: true,
    tags: ["wellness", "mindfulness", "journaling", "retreat", "newcomer"],
    coverGradient: "linear-gradient(135deg,#0F2027,#203A43)",
    organizerName: "Mindful BLR",
  },
  {
    eventID: 460,
    eventTitle: "Arijit Singh Live — World Tour 2025",
    image: "/assets/images/music.png",
    eventCategory: "Music",
    address: "MMRDA Grounds, BKC, Mumbai-400051",
    city: "Mumbai",
    totalSpots: 60000,
    spotsLeft: 18000,
    price: 1499,
    date: "Apr 12",
    time: "7:00 PM",
    roomsLeft: 420,
    compatibilityScore: 97,
    isNewcomerFriendly: false,
    isTrending: true,
    isFeatured: true,
    isVerified: true,
    tags: ["music", "concert", "celebrity", "bollywood"],
    coverGradient: "linear-gradient(135deg,#0A0A1E,#1E1060)",
    organizerName: "Wizcraft International",
  },
]



export const usersData = [
  {
    userID: "usr_001",
    name: "Priya Sharma",
    initial: "P",
    fromCity: "Mumbai",
    currentCity: "Bangalore",
    isNewToCity: true,
    arrivalStatus: "Just Arrived",
    compatibilityScore: 94,
    interests: ["Photography", "Yoga", "Café Hopping"],
    personalityVibe: "Creative · Mindful · Adventurous",
    eventsAttended: 4,
    connectionsCount: 3,
    points: 620,
    gradient: "linear-gradient(135deg,#8B3DFF,#D946EF)",
    badge: "Explorer",
    isOnline: true,
  },
  {
    userID: "usr_002",
    name: "Rahul Kumar",
    initial: "R",
    fromCity: "Delhi",
    currentCity: "Bangalore",
    isNewToCity: true,
    arrivalStatus: "Fairly New",
    compatibilityScore: 91,
    interests: ["Tech", "Hiking", "Startups"],
    personalityVibe: "Techy · Ambitious · Outdoorsy",
    eventsAttended: 7,
    connectionsCount: 5,
    points: 980,
    gradient: "linear-gradient(135deg,#2563EB,#7C3AED)",
    badge: "Connector",
    isOnline: false,
  },
  {
    userID: "usr_003",
    name: "Meera Thapar",
    initial: "M",
    fromCity: "Chennai",
    currentCity: "Bangalore",
    isNewToCity: true,
    arrivalStatus: "Just Arrived",
    compatibilityScore: 88,
    interests: ["Music", "Art", "Reading"],
    personalityVibe: "Creative · Quiet · Cultural",
    eventsAttended: 2,
    connectionsCount: 1,
    points: 280,
    gradient: "linear-gradient(135deg,#059669,#0D9488)",
    badge: "First Timer",
    isOnline: true,
  },
  {
    userID: "usr_004",
    name: "Vikram Nair",
    initial: "V",
    fromCity: "Pune",
    currentCity: "Bangalore",
    isNewToCity: false,
    arrivalStatus: "Lived Here",
    compatibilityScore: 85,
    interests: ["Startups", "Food", "Badminton"],
    personalityVibe: "Energetic · Social · Sporty",
    eventsAttended: 14,
    connectionsCount: 12,
    points: 1840,
    gradient: "linear-gradient(135deg,#D97706,#DC2626)",
    badge: "Social Butterfly",
    isOnline: true,
  },
  {
    userID: "usr_005",
    name: "Shreya Lal",
    initial: "S",
    fromCity: "Hyderabad",
    currentCity: "Bangalore",
    isNewToCity: true,
    arrivalStatus: "Fairly New",
    compatibilityScore: 83,
    interests: ["Dance", "Café Hopping", "Comedy"],
    personalityVibe: "Bubbly · Spontaneous · Fun",
    eventsAttended: 5,
    connectionsCount: 4,
    points: 710,
    gradient: "linear-gradient(135deg,#DB2777,#9333EA)",
    badge: "Explorer",
    isOnline: false,
  },
  {
    userID: "usr_006",
    name: "Aryan Mehta",
    initial: "A",
    fromCity: "Ahmedabad",
    currentCity: "Bangalore",
    isNewToCity: true,
    arrivalStatus: "Just Arrived",
    compatibilityScore: 80,
    interests: ["Coding", "Gaming", "Hackathons"],
    personalityVibe: "Analytical · Quiet · Builder",
    eventsAttended: 1,
    connectionsCount: 0,
    points: 150,
    gradient: "linear-gradient(135deg,#0369A1,#0891B2)",
    badge: "First Timer",
    isOnline: true,
  },
  {
    userID: "usr_007",
    name: "Kavya Reddy",
    initial: "K",
    fromCity: "Vijayawada",
    currentCity: "Hyderabad",
    isNewToCity: true,
    arrivalStatus: "Fairly New",
    compatibilityScore: 78,
    interests: ["Yoga", "Cooking", "Meditation"],
    personalityVibe: "Calm · Wellness · Mindful",
    eventsAttended: 3,
    connectionsCount: 2,
    points: 420,
    gradient: "linear-gradient(135deg,#065F46,#0F766E)",
    badge: "Wellness Seeker",
    isOnline: false,
  },
  {
    userID: "usr_008",
    name: "Nikhil Joshi",
    initial: "N",
    fromCity: "Nagpur",
    currentCity: "Mumbai",
    isNewToCity: true,
    arrivalStatus: "Just Arrived",
    compatibilityScore: 76,
    interests: ["Music", "Nightlife", "Photography"],
    personalityVibe: "Energetic · Social · Night Owl",
    eventsAttended: 2,
    connectionsCount: 1,
    points: 230,
    gradient: "linear-gradient(135deg,#7C3AED,#DB2777)",
    badge: "First Timer",
    isOnline: true,
  },
  {
    userID: "usr_009",
    name: "Divya Krishnan",
    initial: "D",
    fromCity: "Coimbatore",
    currentCity: "Chennai",
    isNewToCity: true,
    arrivalStatus: "Fairly New",
    compatibilityScore: 74,
    interests: ["Classical Music", "Reading", "Art"],
    personalityVibe: "Introverted · Cultural · Creative",
    eventsAttended: 5,
    connectionsCount: 3,
    points: 580,
    gradient: "linear-gradient(135deg,#6D28D9,#4C1D95)",
    badge: "Culture Vulture",
    isOnline: false,
  },
  {
    userID: "usr_010",
    name: "Rohan Gupta",
    initial: "R",
    fromCity: "Jaipur",
    currentCity: "Delhi",
    isNewToCity: true,
    arrivalStatus: "Just Arrived",
    compatibilityScore: 72,
    interests: ["Startups", "Public Speaking", "Networking"],
    personalityVibe: "Ambitious · Extroverted · Leader",
    eventsAttended: 3,
    connectionsCount: 4,
    points: 490,
    gradient: "linear-gradient(135deg,#B45309,#D97706)",
    badge: "Networker",
    isOnline: true,
  },
  {
    userID: "usr_011",
    name: "Ananya Singh",
    initial: "A",
    fromCity: "Lucknow",
    currentCity: "Delhi",
    isNewToCity: true,
    arrivalStatus: "Fairly New",
    compatibilityScore: 70,
    interests: ["Dance", "Yoga", "Travel"],
    personalityVibe: "Energetic · Free Spirit · Adventurous",
    eventsAttended: 6,
    connectionsCount: 5,
    points: 790,
    gradient: "linear-gradient(135deg,#BE185D,#9D174D)",
    badge: "Explorer",
    isOnline: false,
  },
  {
    userID: "usr_012",
    name: "Karan Malhotra",
    initial: "K",
    fromCity: "Chandigarh",
    currentCity: "Delhi",
    isNewToCity: false,
    arrivalStatus: "Lived Here",
    compatibilityScore: 68,
    interests: ["Fitness", "Football", "Nutrition"],
    personalityVibe: "Athletic · Disciplined · Social",
    eventsAttended: 11,
    connectionsCount: 9,
    points: 1320,
    gradient: "linear-gradient(135deg,#15803D,#166534)",
    badge: "Fitness Seeker",
    isOnline: true,
  },
  {
    userID: "usr_013",
    name: "Simran Kaur",
    initial: "S",
    fromCity: "Amritsar",
    currentCity: "Mumbai",
    isNewToCity: true,
    arrivalStatus: "Just Arrived",
    compatibilityScore: 66,
    interests: ["Music", "Cooking", "Travel"],
    personalityVibe: "Warm · Social · Spontaneous",
    eventsAttended: 1,
    connectionsCount: 0,
    points: 100,
    gradient: "linear-gradient(135deg,#C2410C,#EA580C)",
    badge: "First Timer",
    isOnline: false,
  },
  {
    userID: "usr_014",
    name: "Tarun Bhat",
    initial: "T",
    fromCity: "Srinagar",
    currentCity: "Pune",
    isNewToCity: true,
    arrivalStatus: "Fairly New",
    compatibilityScore: 64,
    interests: ["Trekking", "Photography", "Cycling"],
    personalityVibe: "Adventurous · Quiet · Nature Lover",
    eventsAttended: 4,
    connectionsCount: 2,
    points: 460,
    gradient: "linear-gradient(135deg,#0E7490,#0284C7)",
    badge: "Explorer",
    isOnline: true,
  },
  {
    userID: "usr_015",
    name: "Pooja Iyer",
    initial: "P",
    fromCity: "Mysore",
    currentCity: "Bangalore",
    isNewToCity: true,
    arrivalStatus: "Just Arrived",
    compatibilityScore: 62,
    interests: ["Art", "Theatre", "Meditation"],
    personalityVibe: "Creative · Introverted · Thoughtful",
    eventsAttended: 2,
    connectionsCount: 1,
    points: 210,
    gradient: "linear-gradient(135deg,#7C3AED,#6D28D9)",
    badge: "First Timer",
    isOnline: false,
  },
]
 
// ─────────────────────────────────────────────
// GROUP ROOMS DATA
// ─────────────────────────────────────────────
 
export const groupRoomsData = [
  {
    roomID: "room_001",
    roomName: "Weekend Hikers 🌿",
    eventID: 441,
    eventTitle: "Sunrise Trek — Skandagiri Hills",
    vibeCheck: "Chill · Outdoorsy · Tech-Curious",
    members: ["A", "P", "R"],
    memberGradients: [
      "linear-gradient(135deg,#8B3DFF,#D946EF)",
      "linear-gradient(135deg,#2563EB,#7C3AED)",
      "linear-gradient(135deg,#059669,#0D9488)",
    ],
    currentMembers: 4,
    maxMembers: 8,
    compatibilityScore: 87,
    isOpen: true,
    createdBy: "usr_002",
    city: "Bangalore",
  },
  {
    roomID: "room_002",
    roomName: "Café Hoppers ☕",
    eventID: 443,
    eventTitle: "Koramangala Café Hopping Tour",
    vibeCheck: "Social · Foodie · Creative",
    members: ["S", "K"],
    memberGradients: [
      "linear-gradient(135deg,#DB2777,#9333EA)",
      "linear-gradient(135deg,#059669,#0D9488)",
    ],
    currentMembers: 2,
    maxMembers: 6,
    compatibilityScore: 92,
    isOpen: true,
    createdBy: "usr_005",
    city: "Bangalore",
  },
  {
    roomID: "room_003",
    roomName: "Tech Builders 💻",
    eventID: 436,
    eventTitle: "AI & ML Builders Hackathon 2025",
    vibeCheck: "Techy · Ambitious · Young",
    members: ["M", "V", "N", "A", "R"],
    memberGradients: [
      "linear-gradient(135deg,#2563EB,#1D4ED8)",
      "linear-gradient(135deg,#D97706,#B45309)",
      "linear-gradient(135deg,#8B3DFF,#7C3AED)",
      "linear-gradient(135deg,#0369A1,#0891B2)",
      "linear-gradient(135deg,#7C3AED,#DB2777)",
    ],
    currentMembers: 5,
    maxMembers: 8,
    compatibilityScore: 79,
    isOpen: true,
    createdBy: "usr_004",
    city: "Bangalore",
  },
  {
    roomID: "room_004",
    roomName: "Coldplay Squad 🎵",
    eventID: 431,
    eventTitle: "Coldplay Concert — Music of the Spheres",
    vibeCheck: "Energetic · Music Lover · Hype",
    members: ["P", "R", "M", "S"],
    memberGradients: [
      "linear-gradient(135deg,#8B3DFF,#D946EF)",
      "linear-gradient(135deg,#2563EB,#7C3AED)",
      "linear-gradient(135deg,#059669,#0D9488)",
      "linear-gradient(135deg,#DB2777,#9333EA)",
    ],
    currentMembers: 4,
    maxMembers: 6,
    compatibilityScore: 95,
    isOpen: false,
    createdBy: "usr_001",
    city: "Mumbai",
  },
  {
    roomID: "room_005",
    roomName: "Lens Gang 📸",
    eventID: 438,
    eventTitle: "Photography Walk — Cubbon Park",
    vibeCheck: "Creative · Morning · Artsy",
    members: ["D", "P", "T"],
    memberGradients: [
      "linear-gradient(135deg,#6D28D9,#4C1D95)",
      "linear-gradient(135deg,#7C3AED,#6D28D9)",
      "linear-gradient(135deg,#0E7490,#0284C7)",
    ],
    currentMembers: 3,
    maxMembers: 6,
    compatibilityScore: 90,
    isOpen: true,
    createdBy: "usr_009",
    city: "Bangalore",
  },
  {
    roomID: "room_006",
    roomName: "Salsa Beginners 💃",
    eventID: 455,
    eventTitle: "Salsa & Bachata Dance Workshop",
    vibeCheck: "Fun · Spontaneous · Social",
    members: ["S", "A", "K"],
    memberGradients: [
      "linear-gradient(135deg,#DB2777,#9333EA)",
      "linear-gradient(135deg,#BE185D,#9D174D)",
      "linear-gradient(135deg,#065F46,#0F766E)",
    ],
    currentMembers: 3,
    maxMembers: 8,
    compatibilityScore: 83,
    isOpen: true,
    createdBy: "usr_011",
    city: "Bangalore",
  },
  {
    roomID: "room_007",
    roomName: "Startup Crew 🚀",
    eventID: 442,
    eventTitle: "Startup Founders Networking Night",
    vibeCheck: "Ambitious · Professional · Bold",
    members: ["R", "V", "K"],
    memberGradients: [
      "linear-gradient(135deg,#B45309,#D97706)",
      "linear-gradient(135deg,#D97706,#DC2626)",
      "linear-gradient(135deg,#15803D,#166534)",
    ],
    currentMembers: 3,
    maxMembers: 6,
    compatibilityScore: 85,
    isOpen: true,
    createdBy: "usr_010",
    city: "Bangalore",
  },
  {
    roomID: "room_008",
    roomName: "Comedy Night Crew 😂",
    eventID: 454,
    eventTitle: "Stand-Up Comedy Night — Biswa Kalyan Rath",
    vibeCheck: "Funny · Chill · Night Out",
    members: ["S", "N", "A"],
    memberGradients: [
      "linear-gradient(135deg,#DB2777,#9333EA)",
      "linear-gradient(135deg,#7C3AED,#DB2777)",
      "linear-gradient(135deg,#8B3DFF,#D946EF)",
    ],
    currentMembers: 3,
    maxMembers: 6,
    compatibilityScore: 88,
    isOpen: true,
    createdBy: "usr_005",
    city: "Bangalore",
  },
  {
    roomID: "room_009",
    roomName: "Wellness Warriors 🧘",
    eventID: 444,
    eventTitle: "Morning Yoga & Meditation — Cubbon Park",
    vibeCheck: "Mindful · Calm · Early Bird",
    members: ["K", "D", "P"],
    memberGradients: [
      "linear-gradient(135deg,#065F46,#0F766E)",
      "linear-gradient(135deg,#6D28D9,#4C1D95)",
      "linear-gradient(135deg,#7C3AED,#6D28D9)",
    ],
    currentMembers: 3,
    maxMembers: 8,
    compatibilityScore: 81,
    isOpen: true,
    createdBy: "usr_007",
    city: "Bangalore",
  },
  {
    roomID: "room_010",
    roomName: "Arijit Fans 🎤",
    eventID: 460,
    eventTitle: "Arijit Singh Live — World Tour 2025",
    vibeCheck: "Emotional · Music Lover · Soulful",
    members: ["S", "P", "D", "A", "M"],
    memberGradients: [
      "linear-gradient(135deg,#C2410C,#EA580C)",
      "linear-gradient(135deg,#8B3DFF,#D946EF)",
      "linear-gradient(135deg,#6D28D9,#4C1D95)",
      "linear-gradient(135deg,#BE185D,#9D174D)",
      "linear-gradient(135deg,#059669,#0D9488)",
    ],
    currentMembers: 5,
    maxMembers: 8,
    compatibilityScore: 93,
    isOpen: true,
    createdBy: "usr_013",
    city: "Mumbai",
  },
]
